version: '3.9'
services:
  awscliv2:
    build: .docker/aws-cli
    volumes:
    - ~/.aws:/root/.aws
    command: '--version'

  awslocal:
    image: localstack/localstack
    environment:
      DATA_DIR: /tmp/localstack/data
      HOSTNAME_EXTERNAL: localstack
      SERVICES: 'cloudformation,s3,sqs'
    ports:
      - "${SURF_AWSLOCAL_PORT:-4566}:4566"
    volumes:
      - ./.docker/localstack/init.d:/docker-entrypoint-initaws.d
      - ./:/app

  mail:
    image: mailhog/mailhog:latest
    ports:
      - "${SURF_MAIL_UI_PORT:-8025}:8025"

  webserver:
    build:
      context: ./
      dockerfile: .docker/nginx/Dockerfile
    depends_on:
      - laravel
    environment:
      UPSTREAM_HOST: laravel
      CORS_ORIGIN: "${APP_URL:-http://localhost}"
    volumes:
      - ./.docker/tls:/var/tls
      - ./public:/var/www/public
    ports:
      - "${SURF_APP_PORT:-80}:80"
      - "${SURF_APP_TLS_PORT:-443}:443"
      - "${SURF_VITE_HMR_PORT:-5173}:5173"

  laravel:
    build:
      context: ./
      dockerfile: .docker/php-fpm/Dockerfile
    depends_on:
      - database
      - cache
    environment:
      SURF_USER_ID: "${SURF_USER_ID}"
    expose:
        - "5173"
    volumes:
      - ./:/var/www
      - ~/.ssh:/home/www-data/.ssh
      - ~/.composer:/home/www-data/.composer
      - ~/.aws:/larasurf/aws
      - ./.docker/tls:/var/tls

  database:
    image: mysql:8.0
    ports:
      - "${SURF_DB_PORT:-3306}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: supersecret
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: supersecret
    volumes:
      - 'database:/var/lib/mysql'
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-psupersecret']
      retries: 3
      timeout: 5s

  cache:
    image: redis:alpine
    ports:
      - "${SURF_CACHE_PORT:-6379}:6379"
    volumes:
      - 'cache:/data'
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      retries: 3
      timeout: 5s

volumes:
  database:
    driver: local
  cache:
    driver: local
