version: '3.9'
services:
  awslocal:
    image: localstack/localstack
    environment:
      DATA_DIR: /tmp/localstack/data
      HOSTNAME_EXTERNAL: localstack
      SERVICES: 'cloudformation,s3,sqs'
    ports:
      - "${SURF_AWSLOCAL_PORT:-4566}:4566"
    volumes:
      - './.docker/localstack/init.d:/docker-entrypoint-initaws.d'
      - './:/app'

  mail:
    image: mailhog/mailhog:latest
    ports:
      - "${SURF_MAIL_UI_PORT:-8025}:8025"

  webserver:
    build:
      context: ./
      dockerfile: .docker/nginx/Dockerfile
    depends_on:
      - laravel
    environment:
      UPSTREAM_HOST: laravel
    volumes:
      - ./.docker/ssl:/var/ssl
      - ./public:/var/www/public
    ports:
      - "${SURF_APP_PORT:-80}:80"
      - "${SURF_APP_SSL_PORT:-443}:443"

  laravel:
    build:
      context: ./
      dockerfile: .docker/php-fpm/Dockerfile
    depends_on:
      - database
      - cache
    environment:
      AWS_ENDPOINT: http://awslocal:4566
      AWS_ACCESS_KEY_ID: local
      AWS_SECRET_ACCESS_KEY: local
      AWS_DEFAULT_REGION: us-east-1
      AWS_BUCKET: laravel
      AWS_USE_PATH_STYLE_ENDPOINT: 'true'
      AWS_URL: http://localhost:${SURF_AWSLOCAL_PORT:-4566}/laravel
      CACHE_DRIVER: redis
      DB_CONNECTION: mysql
      DB_DATABASE: laravel_local
      DB_HOST: database
      DB_PASSWORD: supersecret
      DB_PORT: 3306
      DB_USERNAME: laravel_local
      MAIL_HOST: mail
      QUEUE_CONNECTION: sqs
      REDIS_HOST: cache
      REDIS_PORT: 6379
      SQS_QUEUE: laravel
      SQS_PREFIX: http://awslocal:4566/000000000000
    volumes:
      - ./:/var/www
      - ~/.ssh:/root/.ssh
      - ~/.composer:/root/.composer
      - ~/.aws:/larasurf/aws

  database:
    image: mysql:8.0
    ports:
      - "${SURF_DB_PORT:-3306}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: supersecret
      MYSQL_DATABASE: laravel_local
      MYSQL_USER: laravel_local
      MYSQL_PASSWORD: supersecret
    volumes:
      - 'database:/var/lib/mysql'
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-psupersecret']
      retries: 3
      timeout: 5s

  cache:
    image: redis:alpine
    ports:
      - "${SURF_CACHE_PORT:-6379}:6379"
    volumes:
      - 'cache:/data'
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      retries: 3
      timeout: 5s

volumes:
  database:
    driver: local
  cache:
    driver: local
