FROM nginx:1.18-alpine

ENV UPSTREAM_HOST localhost
ENV UPSTREAM_PORT 9000

COPY .docker/nginx/laravel.conf.template.cloud /etc/nginx/templates/default.conf.template

COPY public /var/www/public

WORKDIR /var/www/public
